[colors.bright]
black = "0x969896"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xffffff"
yellow = "0xf0c674"

[colors.normal]
black = "0x1d1f21"
blue = "0x81a2be"
cyan = "0x8abeb7"
green = "0xb5bd68"
magenta = "0xb294bb"
red = "0xcc6666"
white = "0xc5c8c6"
yellow = "0xf0c674"

[colors.primary]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[font.bold]
family = "mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "mononoki Nerd Font"
style = "Bold Italic"

[font.italic]
family = "mononoki Nerd Font"
style = "Italic"

[font.normal]
family = "mononoki Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"

[terminal.shell]
args = ["-l"]
program = "zsh"

[window]
decorations = "none"
opacity = 0.95

[terminal]
