#!/bin/bash

echo "Setting up the stuff..."

if [[ "$(uname -a)" == *"Ubuntu"*  ]]
then
    echo "Updating Ubuntu"
    sudo apt update && sudo apt upgrade
    echo "Installing tools/utils"
    sudo apt install ripgrep fd-find make stow tmux awesome compton dmenu nitrogen acpi acpid qt5ct

    echo "Enabling acpid"
    systemctl enable acpid
else
    echo "Updating Arch"
    sudo pacman -Syyu
    echo "Installing tools/utils"
    sudo pacman -S ripgrep fd neovim make stow tmux
fi


# tmux plugin manager and theme
echo "Installing tmux plugin manager... Don't forget to press <C-a><S-i> in a new tmux session later"
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

add_to_file() {
    if grep -Fxq "$1" $2
    then
        echo "Found existing line '$1' in file '$2'"
    else
        echo "Adding line \"$1\" to file \"$2\""
        echo "$1" >> $2
    fi
}

nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# Add aliases to zshrc
add_to_file "alias nv='nvim'" "$HOME/.zshrc"

