#!/usr/bin/env bash

autorandr -l dual
pkill polybar
polybar & 
WALLPAPER="current.jpg"
feh --bg-center "$HOME/wallpapers/$WALLPAPER"
systemctl --user start gnome-keyring-daemon.service &
pkill picom
picom &
pkill nm-applet
nm-applet &
pkill volumeicon
volumeicon &


bspc monitor -d I II III IV V VI VII VIII IX X


pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          8
bspc config focused_border_color \#6666FF
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Resize is super laggy otherwise!
bspc config pointer_motion_interval 50 
