#!/usr/bin/env bash

autorandr -l dual

# Kill some of the stuff we usually start
pkill volumeicon
pkill polybar
pkill picom
pkill nm-applet

# Start up some things
WALLPAPER="current.jpg"
feh --bg-center "$HOME/wallpapers/$WALLPAPER"
systemctl --user start gnome-keyring-daemon.service &
systemctl --user start spotifyd &
picom &
nm-applet &
volumeicon &
# polybar main & 
$HOME/.config/polybar/launch.sh

# Ensure we have the correct cursor
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d chat dev web misc music

bspc config border_width         1
bspc config window_gap          8
bspc config focused_border_color \#6666FF
bspc config normal_border_color  \#1d2021

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Resize is super laggy otherwise!
bspc config pointer_motion_interval 50 
