#!/bin/bash

echo "Loading nvidia_drm"
sudo modprobe nvidia_drm

echo "Setting graphics mode to Integrated"
supergfxctl -m Integrated

echo "Restarting libvirtd"
sudo systemctl restart --now libvirtd
