#!/bin/bash


echo "Setting graphics mode to Integrated"
supergfxctl -m Integrated

echo "Loading nvidia_drm"
sudo modprobe nvidia_drm

echo "Restarting libvirtd"
sudo systemctl restart --now libvirtd
