# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
# export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(zsh-autosuggestions zsh-completions git rust)

# zsh-completions
# fpath+=${ZSH_CUSTOM:-${ZSH:-~/.oh-my-zsh}/custom}/plugins/zsh-completions/src

# source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# Show full path in prompt
PROMPT=${PROMPT/\%c/\%~}


# Set LS_COLORS (molokai generated by vivid)
export LS_COLORS="so=0;38;2;0;0;0;48;2;249;38;114:su=0:*~=0;38;2;122;112;112:mh=0:di=0;38;2;102;217;239:sg=0:ln=0;38;2;249;38;114:cd=0;38;2;249;38;114;48;2;51;51;51:rs=0:mi=0;38;2;0;0;0;48;2;255;74;68:bd=0;38;2;102;217;239;48;2;51;51;51:pi=0;38;2;0;0;0;48;2;102;217;239:st=0:no=0:do=0;38;2;0;0;0;48;2;249;38;114:ow=0:or=0;38;2;0;0;0;48;2;255;74;68:ex=1;38;2;249;38;114:fi=0:ca=0:tw=0:*.h=0;38;2;0;255;135:*.z=4;38;2;249;38;114:*.r=0;38;2;0;255;135:*.c=0;38;2;0;255;135:*.p=0;38;2;0;255;135:*.a=1;38;2;249;38;114:*.o=0;38;2;122;112;112:*.t=0;38;2;0;255;135:*.m=0;38;2;0;255;135:*.d=0;38;2;0;255;135:*.rb=0;38;2;0;255;135:*.pm=0;38;2;0;255;135:*.pl=0;38;2;0;255;135:*.7z=4;38;2;249;38;114:*.la=0;38;2;122;112;112:*.md=0;38;2;226;209;57:*css=0;38;2;0;255;135:*.py=0;38;2;0;255;135:*.ll=0;38;2;0;255;135:*.gz=4;38;2;249;38;114:*.ps=0;38;2;230;219;116:*.lo=0;38;2;122;112;112:*.di=0;38;2;0;255;135:*.xz=4;38;2;249;38;114:*.cr=0;38;2;0;255;135:*.mn=0;38;2;0;255;135:*.cp=0;38;2;0;255;135:*.rs=0;38;2;0;255;135:*.fs=0;38;2;0;255;135:*.kt=0;38;2;0;255;135:*.el=0;38;2;0;255;135:*.ko=1;38;2;249;38;114:*.ex=0;38;2;0;255;135:*.td=0;38;2;0;255;135:*.hh=0;38;2;0;255;135:*.nb=0;38;2;0;255;135:*.cc=0;38;2;0;255;135:*.js=0;38;2;0;255;135:*.sh=0;38;2;0;255;135:*.cs=0;38;2;0;255;135:*.hi=0;38;2;122;112;112:*.gv=0;38;2;0;255;135:*.as=0;38;2;0;255;135:*.go=0;38;2;0;255;135:*.pp=0;38;2;0;255;135:*.bz=4;38;2;249;38;114:*.ml=0;38;2;0;255;135:*.jl=0;38;2;0;255;135:*.ui=0;38;2;166;226;46:*.rm=0;38;2;253;151;31:*.wv=0;38;2;253;151;31:*.ts=0;38;2;0;255;135:*.so=1;38;2;249;38;114:*.hs=0;38;2;0;255;135:*.bc=0;38;2;122;112;112:*.vb=0;38;2;0;255;135:*.doc=0;38;2;230;219;116:*.fsi=0;38;2;0;255;135:*.tml=0;38;2;166;226;46:*.mp4=0;38;2;253;151;31:*.iso=4;38;2;249;38;114:*.pro=0;38;2;166;226;46:*.tif=0;38;2;253;151;31:*.bbl=0;38;2;122;112;112:*.cfg=0;38;2;166;226;46:*.pdf=0;38;2;230;219;116:*.inl=0;38;2;0;255;135:*.mpg=0;38;2;253;151;31:*.odp=0;38;2;230;219;116:*.toc=0;38;2;122;112;112:*.elm=0;38;2;0;255;135:*.erl=0;38;2;0;255;135:*.pod=0;38;2;0;255;135:*.dll=1;38;2;249;38;114:*.img=4;38;2;249;38;114:*.mkv=0;38;2;253;151;31:*.tsx=0;38;2;0;255;135:*.php=0;38;2;0;255;135:*.apk=4;38;2;249;38;114:*.inc=0;38;2;0;255;135:*.rar=4;38;2;249;38;114:*.zst=4;38;2;249;38;114:*.tmp=0;38;2;122;112;112:*.xcf=0;38;2;253;151;31:*.m4v=0;38;2;253;151;31:*.csx=0;38;2;0;255;135:*.csv=0;38;2;226;209;57:*.rpm=4;38;2;249;38;114:*.mir=0;38;2;0;255;135:*.mli=0;38;2;0;255;135:*.com=1;38;2;249;38;114:*.aux=0;38;2;122;112;112:*.jpg=0;38;2;253;151;31:*.dot=0;38;2;0;255;135:*.tgz=4;38;2;249;38;114:*.pas=0;38;2;0;255;135:*.ics=0;38;2;230;219;116:*.ini=0;38;2;166;226;46:*.vob=0;38;2;253;151;31:*.lua=0;38;2;0;255;135:*.pbm=0;38;2;253;151;31:*.pid=0;38;2;122;112;112:*.eps=0;38;2;253;151;31:*.dox=0;38;2;166;226;46:*.psd=0;38;2;253;151;31:*.bag=4;38;2;249;38;114:*.dmg=4;38;2;249;38;114:*.ind=0;38;2;122;112;112:*.clj=0;38;2;0;255;135:*.ico=0;38;2;253;151;31:*.sxw=0;38;2;230;219;116:*.ods=0;38;2;230;219;116:*.tcl=0;38;2;0;255;135:*.ipp=0;38;2;0;255;135:*.exs=0;38;2;0;255;135:*.bak=0;38;2;122;112;112:*.bz2=4;38;2;249;38;114:*.bsh=0;38;2;0;255;135:*.kts=0;38;2;0;255;135:*.ppt=0;38;2;230;219;116:*.fsx=0;38;2;0;255;135:*.htc=0;38;2;0;255;135:*.bcf=0;38;2;122;112;112:*.log=0;38;2;122;112;112:*.tbz=4;38;2;249;38;114:*.bst=0;38;2;166;226;46:*.cxx=0;38;2;0;255;135:*.cpp=0;38;2;0;255;135:*.htm=0;38;2;226;209;57:*TODO=1:*.flv=0;38;2;253;151;31:*.pkg=4;38;2;249;38;114:*.arj=4;38;2;249;38;114:*.tex=0;38;2;0;255;135:*hgrc=0;38;2;166;226;46:*.wma=0;38;2;253;151;31:*.gvy=0;38;2;0;255;135:*.bat=1;38;2;249;38;114:*.exe=1;38;2;249;38;114:*.swp=0;38;2;122;112;112:*.fls=0;38;2;122;112;112:*.idx=0;38;2;122;112;112:*.def=0;38;2;0;255;135:*.pps=0;38;2;230;219;116:*.xlr=0;38;2;230;219;116:*.rst=0;38;2;226;209;57:*.xml=0;38;2;226;209;57:*.bmp=0;38;2;253;151;31:*.zip=4;38;2;249;38;114:*.pgm=0;38;2;253;151;31:*.deb=4;38;2;249;38;114:*.avi=0;38;2;253;151;31:*.h++=0;38;2;0;255;135:*.wav=0;38;2;253;151;31:*.kex=0;38;2;230;219;116:*.mp3=0;38;2;253;151;31:*.tar=4;38;2;249;38;114:*.vcd=4;38;2;249;38;114:*.wmv=0;38;2;253;151;31:*.aif=0;38;2;253;151;31:*.dpr=0;38;2;0;255;135:*.epp=0;38;2;0;255;135:*.c++=0;38;2;0;255;135:*.ttf=0;38;2;253;151;31:*.sql=0;38;2;0;255;135:*.ppm=0;38;2;253;151;31:*.nix=0;38;2;166;226;46:*.ps1=0;38;2;0;255;135:*.xls=0;38;2;230;219;116:*.bin=4;38;2;249;38;114:*.asa=0;38;2;0;255;135:*.mov=0;38;2;253;151;31:*.pyd=0;38;2;122;112;112:*.git=0;38;2;122;112;112:*.hpp=0;38;2;0;255;135:*.mid=0;38;2;253;151;31:*.sty=0;38;2;122;112;112:*.fon=0;38;2;253;151;31:*.pyo=0;38;2;122;112;112:*.jar=4;38;2;249;38;114:*.sxi=0;38;2;230;219;116:*.xmp=0;38;2;166;226;46:*.ltx=0;38;2;0;255;135:*.sbt=0;38;2;0;255;135:*.otf=0;38;2;253;151;31:*.ogg=0;38;2;253;151;31:*.vim=0;38;2;0;255;135:*.m4a=0;38;2;253;151;31:*.zsh=0;38;2;0;255;135:*.swf=0;38;2;253;151;31:*.odt=0;38;2;230;219;116:*.txt=0;38;2;226;209;57:*.out=0;38;2;122;112;112:*.pyc=0;38;2;122;112;112:*.svg=0;38;2;253;151;31:*.gif=0;38;2;253;151;31:*.png=0;38;2;253;151;31:*.cgi=0;38;2;0;255;135:*.blg=0;38;2;122;112;112:*.awk=0;38;2;0;255;135:*.bib=0;38;2;166;226;46:*.yml=0;38;2;166;226;46:*.fnt=0;38;2;253;151;31:*.rtf=0;38;2;230;219;116:*.ilg=0;38;2;122;112;112:*.hxx=0;38;2;0;255;135:*.jpeg=0;38;2;253;151;31:*.mpeg=0;38;2;253;151;31:*.psd1=0;38;2;0;255;135:*.tbz2=4;38;2;249;38;114:*.opus=0;38;2;253;151;31:*.toml=0;38;2;166;226;46:*.yaml=0;38;2;166;226;46:*.lisp=0;38;2;0;255;135:*.orig=0;38;2;122;112;112:*.hgrc=0;38;2;166;226;46:*.tiff=0;38;2;253;151;31:*.html=0;38;2;226;209;57:*.diff=0;38;2;0;255;135:*.purs=0;38;2;0;255;135:*.h264=0;38;2;253;151;31:*.java=0;38;2;0;255;135:*.make=0;38;2;166;226;46:*.flac=0;38;2;253;151;31:*.conf=0;38;2;166;226;46:*.bash=0;38;2;0;255;135:*.webm=0;38;2;253;151;31:*.lock=0;38;2;122;112;112:*.docx=0;38;2;230;219;116:*.xlsx=0;38;2;230;219;116:*.dart=0;38;2;0;255;135:*.pptx=0;38;2;230;219;116:*.rlib=0;38;2;122;112;112:*.json=0;38;2;166;226;46:*.fish=0;38;2;0;255;135:*.psm1=0;38;2;0;255;135:*.epub=0;38;2;230;219;116:*.less=0;38;2;0;255;135:*.scala=0;38;2;0;255;135:*.patch=0;38;2;0;255;135:*.dyn_o=0;38;2;122;112;112:*.cabal=0;38;2;0;255;135:*.toast=4;38;2;249;38;114:*.shtml=0;38;2;226;209;57:*.ipynb=0;38;2;0;255;135:*shadow=0;38;2;166;226;46:*.xhtml=0;38;2;226;209;57:*.cache=0;38;2;122;112;112:*.class=0;38;2;122;112;112:*.cmake=0;38;2;166;226;46:*README=0;38;2;0;0;0;48;2;230;219;116:*.swift=0;38;2;0;255;135:*passwd=0;38;2;166;226;46:*.mdown=0;38;2;226;209;57:*.matlab=0;38;2;0;255;135:*.groovy=0;38;2;0;255;135:*INSTALL=0;38;2;0;0;0;48;2;230;219;116:*COPYING=0;38;2;182;182;182:*.dyn_hi=0;38;2;122;112;112:*.flake8=0;38;2;166;226;46:*.gradle=0;38;2;0;255;135:*.config=0;38;2;166;226;46:*.ignore=0;38;2;166;226;46:*TODO.md=1:*LICENSE=0;38;2;182;182;182:*Makefile=0;38;2;166;226;46:*setup.py=0;38;2;166;226;46:*.gemspec=0;38;2;166;226;46:*Doxyfile=0;38;2;166;226;46:*.desktop=0;38;2;166;226;46:*TODO.txt=1:*README.md=0;38;2;0;0;0;48;2;230;219;116:*.fdignore=0;38;2;166;226;46:*.rgignore=0;38;2;166;226;46:*COPYRIGHT=0;38;2;182;182;182:*.kdevelop=0;38;2;166;226;46:*configure=0;38;2;166;226;46:*.cmake.in=0;38;2;166;226;46:*.DS_Store=0;38;2;122;112;112:*.markdown=0;38;2;226;209;57:*.scons_opt=0;38;2;122;112;112:*README.txt=0;38;2;0;0;0;48;2;230;219;116:*.gitignore=0;38;2;166;226;46:*.gitconfig=0;38;2;166;226;46:*SConstruct=0;38;2;166;226;46:*Dockerfile=0;38;2;166;226;46:*SConscript=0;38;2;166;226;46:*CODEOWNERS=0;38;2;166;226;46:*.localized=0;38;2;122;112;112:*INSTALL.md=0;38;2;0;0;0;48;2;230;219;116:*Makefile.am=0;38;2;166;226;46:*.gitmodules=0;38;2;166;226;46:*Makefile.in=0;38;2;122;112;112:*.travis.yml=0;38;2;230;219;116:*MANIFEST.in=0;38;2;166;226;46:*LICENSE-MIT=0;38;2;182;182;182:*.synctex.gz=0;38;2;122;112;112:*INSTALL.txt=0;38;2;0;0;0;48;2;230;219;116:*configure.ac=0;38;2;166;226;46:*CONTRIBUTORS=0;38;2;0;0;0;48;2;230;219;116:*.applescript=0;38;2;0;255;135:*appveyor.yml=0;38;2;230;219;116:*.fdb_latexmk=0;38;2;122;112;112:*.clang-format=0;38;2;166;226;46:*CMakeCache.txt=0;38;2;122;112;112:*.gitattributes=0;38;2;166;226;46:*CMakeLists.txt=0;38;2;166;226;46:*LICENSE-APACHE=0;38;2;182;182;182:*CONTRIBUTORS.md=0;38;2;0;0;0;48;2;230;219;116:*requirements.txt=0;38;2;166;226;46:*.sconsign.dblite=0;38;2;122;112;112:*CONTRIBUTORS.txt=0;38;2;0;0;0;48;2;230;219;116:*package-lock.json=0;38;2;122;112;112:*.CFUserTextEncoding=0;38;2;122;112;112"

alias nv='nvim'

# Add things to path
export PATH="$PATH:~/.scripts/"
